{
 "title": "ava node dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "group", "query": "label_values(group)" },
   { "name": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "AVAX NODE STATUS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{group=\"[[group]]\",job=\"[[job]]\"}"
    }
   ]
  },
  {
   "title": "X_handler_put_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gecko_X_handler_put_count{group=\"[[group]]\",job=\"[[job]]\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "P_handler_put_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gecko_P_handler_put_count{group=\"[[group]]\",job=\"[[job]]\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "AVAX NODE STATUS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{group=\"ava\",job=\"avax-node\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": " X Chain vertices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gecko_X_vtx_processing{group=\"[[group]]\",job=\"[[job]]\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "P handler chits count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " gecko_P_handler_chits_count{group=\"[[group]]\",job=\"[[job]]\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "gecko_timestamp_handler_put_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gecko_P_timestamp_handler_put_count{group=\"[[group]]\",job=\"[[job]]\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "P_processing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gecko_P_processing{group=\"[[group]]\",job=\"[[job]]\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gecko_peers{group=\"[[group]]\",job=\"[[job]]\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}